import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Frontend App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      <footer>
          <Link href={"./"}>Home</Link>
          <p>University project, not real data.</p>
      </footer>
      </body>
    </html>
  );
}
