import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import LogoutButton from "@/modules/authModules/logoutButton";
import LoginButton from "@/modules/authModules/loginButton";
import SignInButton from "@/modules/authModules/signInButton";

export const metadata: Metadata = {
  title: "Web Development Assignment Frontend App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div>
          <LoginButton/>
          <SignInButton/>
          <LogoutButton/>
      </div>
        {children}
      <footer>
          <Link href={"../"}>Home</Link>
          <p>University project, not real data.</p>
      </footer>
      </body>
    </html>
  );
}
